Ec2/enable gossip scoring
ChainSafe/forest pull request #1115
Opened 2021-05-25 15:15 UTC by ec2

**Summary of changes**
Changes introduced in this pull request:
- Reintroduces and fixes GossipSub parameters. 

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

2021-05-28 17:27 UTC, cryptoquick commented
Nice! How would this fail if I were to test it?

2021-05-28 19:33 UTC, ec2 commented
> Nice! How would this fail if I were to test it?

Blocks come in with delay, DoS, etc...

2021-05-31 11:40 UTC, creativcoder approved these changes
@ec2 where does this improve things?

2021-05-31 13:55 UTC, cryptoquick requested changes
Just some minor changes

2021-05-31 13:55 UTC, cryptoquick commented on node/forest_libp2p/src/gossip_params.rs
> +        // Set to 0 because disabled for FIlecoin
Misspelled

2021-05-31 13:55 UTC, cryptoquick commented on node/forest_libp2p/src/behaviour.rs
>          // TODO: Figure out why this delays incoming blocks. See gossip_params.rs for the params settings.
Remove

2021-05-31 13:55 UTC, cryptoquick commented on node/forest_libp2p/src/behaviour.rs
> +        gs_config_builder.message_id_fn(msg_id_fn);
Inline closure

2021-05-31 13:55 UTC, cryptoquick commented on node/forest_libp2p/src/gossip_params.rs
> +        time_in_mesh_weight: 0.0002778,
Leave a comment for `// 1/3600`

2021-05-31 15:14 UTC, cryptoquick approved these changes
Awesome! Hopefully this will reduce those warnings we sometimes get, and just generally make us better at scoring peers with libp2p. :rocket:

2021-05-31 15:43 UTC, merged