Connor/chain sync cli
ChainSafe/forest pull request #1175
Opened 2021-06-24 20:03 UTC by connormullett

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

2021-07-09 22:04 UTC, cryptoquick requested changes
I just checked out `sync wait` and `sync status`, and they look really good!

I'm not sure I know how to use `sync check-bad`, or at least, there's no output from that, and I'm not sure why. However, I also acknowledge that this isn't going to work great while we can't sync to mainnet.

Just some other minor nits and comments. Good work on this one, the serialization stuff seemed especially tricky!

2021-07-10 16:15 UTC, connormullett commented
> I'm not sure I know how to use `sync check-bad`, or at least, there's no output from that, and I'm not sure why. However, I also acknowledge that this isn't going to work great while we can't sync to mainnet.

Check bad needs a block to be marked as bad. Otherwise there are no blocks marked as bad. I'll add in a condition to display "No blocks bad" or something if nothing is returned

2021-07-10 16:22 UTC, connormullett commented on node/rpc-client/src/sync_ops.rs
> +}
Good point, fixed.

2021-07-10 16:23 UTC, connormullett commented on forest/src/cli/sync_cmd.rs
> +                    };
👍

2021-07-10 16:24 UTC, connormullett commented on blockchain/chain_sync/src/sync_state.rs
> +    /// Return an Arc clone of the Base [Tipset]
👍

2021-07-10 16:24 UTC, connormullett commented on blockchain/chain_sync/src/sync_state.rs
> +use serde::{Deserialize, Serialize, Serializer};
👍

2021-07-10 17:01 UTC, cryptoquick approved these changes
Great work! Glad my suggestions were helpful.

2021-07-14 16:36 UTC, creativcoder commented on forest/src/cli/sync_cmd.rs
> +                    println!("response");
Feels like an incomplete message?

2021-07-14 16:37 UTC, creativcoder approved these changes
lgtm!

2021-07-20 16:47 UTC, merged