Rest of V5 Updates
ChainSafe/forest pull request #1217
Opened 2021-08-24 16:34 UTC by ec2

**Summary of changes**
Changes introduced in this pull request:
- 

This PR includes the following:
- Updates to the Actor Interface for v5
- All remaining FIPS that are now 0008 or 0013

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

2021-08-30 19:50 UTC, cryptoquick commented
Seeing really weird behavior with the VM taking up all the RAM and then just crawling through the snapshot import. After restarting the VM it looks a little better on the memory usage, but it's still crawling along. The current estimate is that this will take 5 days to import (7300 minutes, to be exact). I even `rm -rf`ed the db dir and copied the snapshot to the local VM SSD in the hopes of improving performance a bit. Not sure if this is consistent with your observations, @ec2 ?

Before:
![Screenshot from 2021-08-30 13-41-33](https://user-images.githubusercontent.com/285690/131396596-fc89bb16-42ab-40a5-9776-434291c019fd.png)
![Screenshot from 2021-08-30 13-42-10](https://user-images.githubusercontent.com/285690/131396615-35a4b3bc-29f2-4a3f-b73a-ddecfc40fd35.png)

Lots of zombie processes maybe?

After reboot, rm -rf, and cp snapshot to home:
![Screenshot from 2021-08-30 13-47-51](https://user-images.githubusercontent.com/285690/131396533-15e6d404-4fb4-4b4f-ace3-6402633812a6.png)
![Screenshot from 2021-08-30 13-48-01](https://user-images.githubusercontent.com/285690/131396544-34cd8fb3-1f67-4679-972c-52dc3654181a.png)

Not sure what's going on. Any changes in this PR that you think might've caused this behavior? I'll try this on my local PC, also.

2021-08-31 03:36 UTC, cryptoquick commented
@ec2 Can you link to a lotus git diff I can compare this against?

2021-08-31 03:37 UTC, cryptoquick commented
Also, you failed the linter :/

2021-09-01 06:24 UTC, cryptoquick requested changes
Everything looks consistent with the go specs actors changes, but I added a couple documentation updates you missed in a PR into this branch:
https://github.com/ChainSafe/forest/pull/1224

Take a look, feel free to merge if it's helpful.

2021-09-01 15:10 UTC, cryptoquick approved these changes
ty for merging muh PR
should be g2g from my end

2021-09-01 16:34 UTC, olibearo approved these changes
Great! Thanks @ec2

2021-09-01 17:34 UTC, cryptoquick commented on utils/bitfield/src/rleplus/mod.rs
> +// a slice of runs, a bitfield of this size should not exceed 2MiB of memory.
@olibearo I believe it says `runs`, which I think makes sense in this context

2021-09-01 17:34 UTC, cryptoquick commented on utils/bitfield/src/rleplus/mod.rs
> +// a slice of runs, a bitfield of this size should not exceed 2MiB of memory.
(assuming RLE stands for Run-Length Encoding)

2021-09-23 19:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/forest?pullRequest=1217) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/forest?pullRequest=1217) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: cryptoquick<br/>:white_check_mark: ec2<br/>:x: Your Name<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/forest?pullRequest=1217) it.</sub>

2021-09-24 23:13 UTC, merged