Add tyshkor to CODEOWNERS.
ChainSafe/forest pull request #1540
Opened 2022-06-20 08:26 UTC by lemmih

**Summary of changes**
Changes introduced in this pull request:
- Add tyshko5 to CODEOWNERS such that he is requested to do code reviews.

**Reference issue to close (if applicable)**

**Other information and links**

2022-06-20 08:36 UTC, LesnyRumcajs requested changes

2022-06-20 08:40 UTC, lemmih commented on .github/CODEOWNERS
> +*       @connormullett @elmattic @lemmih @LesnyRumcajs @jdjaustin @tyshkor5
Hmm, github won't let me apply your fix. :(

2022-06-20 08:42 UTC, LesnyRumcajs approved these changes

2022-06-21 06:56 UTC, elmattic approved these changes

2022-06-21 08:15 UTC, merged