WIP PR 1534 LLVM code coverage
ChainSafe/forest pull request #1558
Opened 2022-06-21 10:40 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes 

**Other information and links**

2022-06-21 16:14 UTC, lemmih commented on .github/workflows/rust.yml
> +        #   args: '--locked --jobs 16 --timeout 600 --skip-clean -- --test-threads 16'
`cargo llvm-cov` takes `--jobs` parameter. We might as well set it to 16.

2022-06-21 16:14 UTC, lemmih commented on .github/workflows/rust.yml
> +        #   args: '--locked --jobs 16 --timeout 600 --skip-clean -- --test-threads 16'
Oh wait, it defaults to the number of available cpus. Yeah, let's leave it then.

2022-06-21 16:15 UTC, lemmih commented on .github/workflows/rust.yml
> +        #   args: '--locked --jobs 16 --timeout 600 --skip-clean -- --test-threads 16'
Let's just remove the commented-out old arguments since we're not using them anymore.

2022-06-22 12:20 UTC, LesnyRumcajs commented
Any high-level wrap-up on the differences and how is it better than `tarpaulin`? Seems the coverage will drop, is this more correct than the current solution?

2022-06-22 12:27 UTC, lemmih commented
> Any high-level wrap-up on the differences and how is it better than `tarpaulin`? Seems the coverage will drop, is this more correct than the current solution?

llvm-cov instruments the source code and will always generate 100% accurate results, even if optimizations are enabled. Tarpaulin interrupts the program every so often to look at the call-stack. It is not 100% accurate at the best of times and optimizations ruin the results entirely. The reason we didn't use it earlier is because it just became stable in rust-1.60.

2022-06-22 12:48 UTC, LesnyRumcajs commented
@lemmih sounds good, seems the coverage dropped because more lines are now taken into consideration.

2022-06-22 12:49 UTC, LesnyRumcajs requested changes
Looks good, but this file needs to be removed: https://github.com/ChainSafe/forest/blob/main/.tarpaulin.toml

2022-06-22 12:53 UTC, lemmih commented
> Looks good, but this file needs to be removed: https://github.com/ChainSafe/forest/blob/main/.tarpaulin.toml

Ah, right. @tyshko5 could you see to that?

2022-06-23 07:16 UTC, LesnyRumcajs approved these changes

2022-06-23 07:16 UTC, merged