Replace UnsignedMessage with fvm_shared::message::Message
ChainSafe/forest pull request #1613
Opened 2022-07-04 10:24 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1599

**Other information and links**

2022-07-06 08:53 UTC, lemmih requested changes

2022-07-06 08:53 UTC, lemmih commented on blockchain/state_manager/src/lib.rs
> +    pub msg: Message,
Will this still be serialized correctly? I really wish we had some tests to verify the desired behavior.

2022-07-06 08:53 UTC, lemmih commented on vm/message/src/signed_message.rs
> +        self.message.gas_fee_cap.clone() * self.message.gas_limit + self.message.value.clone()
```suggestion
        &self.message.gas_fee_cap * self.message.gas_limit + &self.message.value
```

2022-07-06 13:30 UTC, tyshko5 commented on node/rpc-api/src/data_types.rs
> +    pub bls_msg: Vec<Message>,
Fixed it

2022-07-06 13:45 UTC, tyshko5 commented on vm/message/src/signed_message.rs
> +        self.message.gas_fee_cap.clone() * self.message.gas_limit + self.message.value.clone()
Fixed

2022-07-06 13:45 UTC, tyshko5 commented on vm/message/src/chain_message.rs
> +            Self::Unsigned(t) => t.gas_fee_cap.clone() * t.gas_limit + t.value.clone(),
Fixed

2022-07-07 08:41 UTC, lemmih approved these changes

2022-07-07 11:35 UTC, LesnyRumcajs approved these changes

2022-07-07 11:36 UTC, merged