Use consistent error handling.
ChainSafe/forest pull request #1632
Opened 2022-07-11 11:37 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1458

**Other information and links**

2022-07-11 12:35 UTC, lemmih requested changes
Never convert an error to a string unless you have to. Remove all the `map_err`s that you can.

2022-07-11 12:35 UTC, lemmih commented on blockchain/state_manager/src/lib.rs
> +            .map_err(|e| anyhow::anyhow!("{}", e))?
This `map_err` isn't necessary.

2022-07-11 14:06 UTC, lemmih requested changes

2022-07-11 14:07 UTC, tyshko5 commented on utils/net_utils/src/download.rs
> +                return Err(anyhow::anyhow!("{}", DownloadError::HeaderError));
It isn't going to be a string

2022-07-11 14:11 UTC, lemmih commented on utils/net_utils/src/download.rs
> +                return Err(anyhow::anyhow!("{}", DownloadError::HeaderError));
Could you explain that to me?

2022-07-11 14:11 UTC, tyshko5 commented on utils/net_utils/src/download.rs
> +                return Err(anyhow::anyhow!("{}", DownloadError::HeaderError));
But I've changed it to ::new if that's more acceptable

2022-07-11 14:12 UTC, lemmih commented on utils/net_utils/src/download.rs
> +                return Err(anyhow::anyhow!("{}", DownloadError::HeaderError));
`anyhow::anyhow!(DownloadError::HeaderError)` would also have been acceptable.

2022-07-11 15:02 UTC, lemmih approved these changes

2022-07-12 10:41 UTC, lemmih commented
> What about using `.context` instead of `.ok_or_else(|| ..`?

Ah, yes. Much better. I thought `.context` was only defined for `Result` and not `Option`.

2022-07-12 10:51 UTC, LesnyRumcajs approved these changes

2022-07-12 10:51 UTC, LesnyRumcajs commented on blockchain/state_manager/src/lib.rs
> +            .ok_or_else(|| anyhow::anyhow!("genesis header was none"))?;
perhaps `geneis header missing` would be more helpful for those not versed in Rust scriptures

2022-07-13 08:35 UTC, merged