Order-independent configuration for TOML serde
ChainSafe/forest pull request #1743
Opened 2022-07-28 08:49 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1488

**Other information and links**

2022-07-28 09:02 UTC, elmattic commented
The key `miscellaneous` could be better I think, what do you think of `client`? (it's also used in lotus for general settings).

2022-07-28 11:52 UTC, lemmih commented
> The key `miscellaneous` could be better I think, what do you think of `client`? (it's also used in lotus for general settings).

This seems like a good idea. @LesnyRumcajs What do you think?

2022-07-28 12:11 UTC, LesnyRumcajs commented
I vote yes for Lotus naming compatibility. :lotus_position:

2022-07-28 12:16 UTC, LesnyRumcajs reviewed
To `seal` this nice change, it'd be great to add a test that checks if the default config TOML doesn't have any free params. This way, anyone that tries to add a random int to the configuration will get immediately bashed when running tests. What do you think?

2022-07-28 12:32 UTC, lemmih commented
> To `seal` this nice change, it'd be great to add a test that checks if the default config TOML doesn't have any free params. This way, anyone that tries to add a random int to the configuration will get immediately bashed when running tests. What do you think?

How do we test for this?

2022-07-28 12:53 UTC, LesnyRumcajs commented
> > To `seal` this nice change, it'd be great to add a test that checks if the default config TOML doesn't have any free params. This way, anyone that tries to add a random int to the configuration will get immediately bashed when running tests. What do you think?
> 
> How do we test for this?

We check if the generated TOML starts with a section, i.e. `[`. The `free` params always land at the beginning of the file.

2022-07-28 13:35 UTC, lemmih requested changes
Good work. I'll add a new issue for testing that we don't have any free-standing configuration items.

2022-07-28 13:35 UTC, lemmih commented on forest/src/cli/config.rs
> +    pub miscellaneous: Miscellaneous,
As per @elmattic suggestion:

```suggestion
    pub client: Client,
```

2022-08-01 16:09 UTC, LesnyRumcajs approved these changes

2022-08-02 08:51 UTC, elmattic approved these changes

2022-08-02 08:54 UTC, elmattic commented
> Good work. I'll add a new issue for testing that we don't have any free-standing configuration items.

This last task should be done before merging the PR.

2022-08-02 08:57 UTC, merged