heaptrack doc
ChainSafe/forest pull request #1819
Opened 2022-08-12 08:34 UTC by LesnyRumcajs

**Summary of changes**
Changes introduced in this pull request:
- added heaptrack quick start to documents

**Reference issue to close (if applicable)**

Closes https://github.com/ChainSafe/forest/issues/1817

**Other information and links**

2022-08-12 13:14 UTC, lemmih approved these changes
With pictures and everything!

2022-08-17 13:14 UTC, elmattic requested changes
A part a few typos, looks like a really detailed how-to for `heaptrack` 👍.

Possibly will have something to add once I start using this tool but for now looks good to merge.

2022-08-17 13:14 UTC, elmattic commented on documentation/developer_documentation/memory-analysis.md
> +While most of the potential *culpripts* are not necessarily interesting (e.g. `alloc::*`) because even a `String` constructor calls them, we immediately see that among specific ones, it's the `rocksd
Typo on *culprits*.

2022-08-17 13:14 UTC, elmattic commented on documentation/developer_documentation/memory-analysis.md
> +### Miscallenous
Typo on Miscellaneous.

2022-08-17 13:14 UTC, elmattic commented on documentation/developer_documentation/memory-analysis.md
> +- There is a lot of noise coming from dependencies and standard library. It's useful to mentally filter them out a bit and focus on the biggest culprits in Forest methods. Flamegraph and caller/calee
Typo on callee.

2022-08-17 14:55 UTC, elmattic approved these changes

2022-08-17 15:14 UTC, merged