Enable cargo-spellcheck for node
ChainSafe/forest pull request #1824
Opened 2022-08-15 11:41 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1812

**Other information and links**

2022-08-15 16:03 UTC, connormullett approved these changes
LGTM

2022-08-15 17:49 UTC, jdjaustin approved these changes

2022-08-16 10:00 UTC, lemmih requested changes

2022-08-16 10:00 UTC, lemmih commented on .config/forest.dic
> +KV
Maybe we can spell it out as `key-value`.

2022-08-17 10:39 UTC, lemmih approved these changes
Not sure what's the best way to handle `bitswap`.

2022-08-17 10:39 UTC, merged