Enable cargo-spellcheck for node/forest_libp2p
ChainSafe/forest pull request #1832
Opened 2022-08-17 08:32 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #1811

**Other information and links**

2022-08-17 12:17 UTC, lemmih requested changes

2022-08-17 12:17 UTC, lemmih commented on node/forest_libp2p/src/behaviour.rs
> +    /// Bootstrap `Kademlia` network
We have Kademlia in the dictionary.

2022-08-17 12:17 UTC, lemmih commented on node/forest_libp2p/src/behaviour.rs
> +/// Event type which is emitted from the [`ForestBehaviour`] into the Libp2p service.
I think you've used `LibP2P` in other PRs.

2022-08-17 12:17 UTC, lemmih commented on .config/forest.dic
> +Libp2p
There's already `LibP2P` in the dictionary.

2022-08-18 09:27 UTC, lemmih requested changes

2022-08-18 09:27 UTC, lemmih commented on node/forest_libp2p/src/config.rs
> +    /// `Kademlia` discovery enabled.
Kademlia is in the dictionary.

2022-08-18 09:27 UTC, lemmih commented on node/forest_libp2p/src/discovery.rs
> +/// Note: In order to discover nodes or load and store values via `Kademlia` one has to add at least
Kademlia is in the dictionary.

2022-08-18 09:27 UTC, lemmih commented on node/forest_libp2p/src/discovery.rs
> +    /// Configures if `Kademlia` is enabled.
Kademlia is in the dictionary.

2022-08-18 09:27 UTC, lemmih commented on node/forest_libp2p/src/discovery.rs
> +    /// `Kademlia` discovery.
Kademlia is in the dictionary.

2022-08-18 09:27 UTC, lemmih commented on node/forest_libp2p/src/discovery.rs
> +    /// Stream that fires when we need to perform the next random `Kademlia` query.
Kademlia is in the dictionary.

2022-08-18 10:32 UTC, lemmih approved these changes

2022-08-18 21:54 UTC, jdjaustin approved these changes

2022-08-22 13:54 UTC, merged