Define each word in the custom forest.dic dictionary
ChainSafe/forest pull request #1857
Opened 2022-08-29 09:46 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes https://github.com/ChainSafe/forest/issues/1854

**Other information and links**

2022-08-29 10:36 UTC, LesnyRumcajs requested changes

2022-08-29 10:36 UTC, LesnyRumcajs commented on documentation/developer_documentation/glossary.md
> +[_Proof-of-Spacetime_](pos#post) is a procedure by which a [storage-miner](glossary#storage-miner-actor) can prove to the Filecoin network they have stored and continue to store a unique copy of some
all of the links in this section are broken

2022-08-29 10:36 UTC, LesnyRumcajs commented on documentation/developer_documentation/glossary.md
> +[Ralph C. Merkle](https://en.wikipedia.org/wiki/Ralph_Merkle) is a computer scientist. He is one of the inventors of public-key cryptography, the inventor of cryptographic hashing. Merkle tree is nam
Best to provide a link to Merkle tree article, it's probably more interesting to someone looking into the glossary.

2022-08-29 13:40 UTC, LesnyRumcajs commented on documentation/developer_documentation/glossary.md
> +[IPFS](https://github.com/ipfs/ipfs) stands for InterPlanetary File System which is A peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
```suggestion
[IPFS](https://github.com/ipfs/ipfs) stands for InterPlanetary File System which is a peer-to-peer hypermedia protocol to make the web faster, safer, and more open.
```

2022-08-29 14:58 UTC, lemmih commented
@tyshko5 Looks good. Could you update `SUMMARY.md` to include a link to the glossary?

2022-08-30 08:36 UTC, lemmih requested changes

2022-08-30 11:12 UTC, tyshko5 commented on documentation/src/SUMMARY.md
> +- [Glossary](../developer_documentation/glossary.md)
Fixed

2022-08-30 12:06 UTC, lemmih requested changes
Great. We only need one copy of the glossary, though.

2022-08-31 08:15 UTC, lemmih approved these changes

2022-09-01 09:19 UTC, merged