Property Test for Message
ChainSafe/forest pull request #1970
Opened 2022-09-29 19:23 UTC by jdjaustin

**Summary of changes**
Changes introduced in this pull request:
- Use quickcheck to test our custom implementations of `Message`

**Reference issue to close (if applicable)**

Closes associated task in #1881 

**Other information and links**

N/A

2022-09-30 12:57 UTC, lemmih requested changes
Could you refactor the `SignedMessage` testing code to use the same `Arbitrary` impl for `MessageWrapper`?

2022-10-05 08:38 UTC, lemmih requested changes
- Move all the testing code into the `tests` module. You should only require one `#[cfg(test)]`.
- Refactor the code for `MessageWrapper`. We only want one implementation that generates an arbitrary message, not two.

2022-10-06 12:43 UTC, lemmih commented on vm/message/src/message.rs
> +#[cfg(any(feature = "proofs", test))]
This should no longer be necessary.

2022-10-07 09:09 UTC, tyshko5 approved these changes

2022-10-07 09:42 UTC, merged