Property Test for PoStProof
ChainSafe/forest pull request #1991
Opened 2022-10-03 20:38 UTC by jdjaustin

**Summary of changes**
Changes introduced in this pull request:
- Use quickcheck to test our custom implementations of `PoStProof`

**Reference issue to close (if applicable)**

Closes associated task in #1881 

**Other information and links**

N/A

2022-10-04 09:35 UTC, LesnyRumcajs requested changes

2022-10-04 09:35 UTC, LesnyRumcajs commented on types/src/sector/post.rs
> +    }
Same comment as [here](https://github.com/ChainSafe/forest/pull/1982#discussion_r986615383)

2022-10-04 09:35 UTC, LesnyRumcajs commented on types/src/sector/post.rs
> +}
Could this be entirely inside `mod tests` along with the import?

2022-10-07 09:07 UTC, lemmih approved these changes

2022-10-07 09:19 UTC, tyshko5 approved these changes

2022-10-10 08:15 UTC, LesnyRumcajs approved these changes
LGTM, after you merge the changes from the PR introducing workspace dependencies for `quickcheck`, please update the `types/Cargo.toml` and potentially other `.toml` files that would be able to use it.

2022-10-10 08:15 UTC, LesnyRumcajs commented on types/Cargo.toml
> +serde_json                  = "1.0"
use workspace dependencies?

2022-10-10 16:39 UTC, merged