Property Test for KeyInfo
ChainSafe/forest pull request #1992
Opened 2022-10-03 22:14 UTC by jdjaustin

**Summary of changes**
Changes introduced in this pull request:
- Use quickcheck to test our custom implementations of `KeyInfo`

**Reference issue to close (if applicable)**

Closes associated task in #1881 

**Other information and links**

N/A

2022-10-11 07:20 UTC, LesnyRumcajs approved these changes

2022-10-11 07:28 UTC, lemmih requested changes
Merge the two tests modules and make sure you use `KeyInfoJson`.

2022-10-11 13:03 UTC, jdjaustin commented on key_management/Cargo.toml
> +serde_json        = "1.0"
That was the draft commit; this PR has already been updated to use the workspace dependencies.

2022-10-12 07:34 UTC, lemmih requested changes

2022-10-12 07:34 UTC, lemmih commented on key_management/src/keystore.rs
> +    impl quickcheck::Arbitrary for KeyInfoJson {
We want to generate `KeyInfo`s. The `KeyInfoJson` structure is just there to help with the JSON encoding.

2022-10-12 16:15 UTC, lemmih approved these changes

2022-10-12 16:55 UTC, merged