Merge utility crates.
ChainSafe/forest pull request #2037
Opened 2022-10-11 08:48 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes  #2005

**Other information and links**

2022-10-11 11:42 UTC, lemmih requested changes
Could you move `forest_utils` into the `utils/` folder and make a note of why `forest_hash_utils` and `forest_test_utils` couldn't be included in the crate?

2022-10-11 14:11 UTC, tyshko5 commented
`forest_test_utils` cannot be merged as it creates a dependency cycle
`forest_hash_utils ` cannot be merged as `fvm_ipfs_hamt` depends on it

2022-10-11 14:19 UTC, lemmih commented
> `forest_test_utils` cannot be merged as it creates a dependency cycle

What cycle?

> `forest_hash_utils` cannot be merged as `fvm_ipfs_hamt` depends on it

They're depending on `v0.1` which has already been published. Why is it a problem that `fvm_ipld_hamt` needs `forest_hash_utils`?

2022-10-11 14:42 UTC, tyshko5 commented
Recreation of that cycle will take some effort, but it takes 6 packages in a dependency cycle.

2022-10-11 15:18 UTC, lemmih requested changes

2022-10-12 09:24 UTC, tyshko5 commented on utils/forest_utils/Cargo.toml
> +features = ["test_constructors"]
Removed

2022-10-12 12:50 UTC, tyshko5 commented on vm/actor_interface/src/adt/map.rs
> +    pub fn get<Q: ?Sized + fil_actors_runtime_v8::fvm_ipld_hamt::Hash>(
Fixed

2022-10-12 15:12 UTC, tyshko5 commented on utils/forest_utils/Cargo.toml
> +
There were 2 empty lines before, I've deleted one. That's why it's not visible

2022-10-12 15:35 UTC, lemmih requested changes

2022-10-12 15:35 UTC, lemmih commented on vm/actor_interface/src/adt/map.rs
> +use fvm_ipld_hamt::Hash;
```suggestion
use fvm_ipld_hamt::{BytesKey, Hash};
```

2022-10-12 15:35 UTC, lemmih commented on vm/actor_interface/src/adt/map.rs
> +    pub fn get<Q: ?Sized + Hash>(&self, k: &Q) -> Result<Option<&V>, AnyhowError>
Do we need `Hash` here? If yes, why?

```suggestion
    pub fn get<Q: ?Sized>(&self, k: &Q) -> Result<Option<&V>, AnyhowError>
```

2022-10-12 15:35 UTC, lemmih commented on vm/actor_interface/Cargo.toml
> +fvm_ipld_hamt                    = "0.5"
`fvm_ipld_hamt` is part of the workspace.

```suggestion
fvm_ipld_hamt.workspace = true
```

2022-10-13 08:21 UTC, lemmih approved these changes

2022-10-13 10:18 UTC, LesnyRumcajs approved these changes

2022-10-13 10:32 UTC, merged