Remove `CircSupplyCalc` Trait
ChainSafe/forest pull request #2091
Opened 2022-10-18 19:11 UTC by jdjaustin

Co-authored-by: David Himmelstrup <lemmih@gmail.com>

**Summary of changes**
Changes introduced in this pull request:
- The `CircSupplyCalc` no longer serves a purpose. In `VM::new`, replaced `CircSupplyCalc` by an `FnOnce` callback that computes the circulating supply.

**Reference issue to close (if applicable)**

Closes #2031 

**Other information and links**

N/A

2022-10-19 04:57 UTC, lemmih requested changes

2022-10-19 04:57 UTC, lemmih commented on blockchain/state_manager/src/vm_circ_supply.rs
> +        get_circulating_supply(self, height, state_tree)
`get_circulating_supply` isn't used anywhere else so we can just inline it here. And you can change the `get_supply` name to the slightly more descriptive `get_circulating_supply`.

2022-10-19 07:55 UTC, LesnyRumcajs commented on vm/interpreter/src/vm.rs
> +        circ_supply_calc: impl FnOnce(ChainEpoch, &StateTree<&DB>) -> Result<TokenAmount, anyhow::Error>,
Let's not use the shorthand with such a long type. It'd be nicer to put it in the `where` section.

2022-10-19 18:10 UTC, lemmih approved these changes

2022-10-19 18:10 UTC, lemmih commented on blockchain/state_manager/src/lib.rs
> +        self.genesis_info.get_circulating_supply(height, state_tree)
I would have liked this to be inlined such that there is only one `get_circulating_supply` function. But this is also okay.

2022-10-20 07:55 UTC, LesnyRumcajs approved these changes
I like it.

2022-10-20 09:44 UTC, merged