Delete the BlockStore trait, move BlockStoreExt, and delete forest_ipld_blockstore
ChainSafe/forest pull request #2098
Opened 2022-10-19 12:25 UTC by tyshko5

**Summary of changes**
Changes introduced in this pull request:
- 

**Reference issue to close (if applicable)**

Closes #2085

**Other information and links**

2022-10-19 13:50 UTC, lemmih requested changes
I don't think the `Store` trait is required in any of the places where you use it and the `Clone` trait can also be removed most of the time.

There are also a bunch of search&replace mistakes to be fixed.

2022-10-19 13:50 UTC, lemmih commented on blockchain/chain_sync/src/tipset_syncer.rs
> +/// Going forward along the tipsets, try to load the messages in them from the `Blockstore + Store + Clone`,
This is a search&replace mistake.

2022-10-19 13:50 UTC, lemmih commented on blockchain/state_manager/src/lib.rs
> +    /// Returns the cloned [`Arc`] of the state manager's [`Blockstore + Store + Clone`].
More search&replace mistakes.

2022-10-20 17:51 UTC, lemmih approved these changes
Good job. We'll get rid of those lingering `Store` trait constrains in a separate PR.

2022-10-21 11:47 UTC, elmattic approved these changes
Nice PR! I can still see some references to `BlockStore` in some doc comments. Maybe we could update those as well.

2022-10-21 13:23 UTC, merged