chore: release forest v0.6.0
ChainSafe/forest pull request #2384
Opened 2023-01-04 03:03 UTC by jdjaustin

**Summary of changes**
Changes introduced in this pull request:
- Summarize the changes in the upcoming 0.6.0 release.

**Reference issue to close (if applicable)**

N/A

**Other information and links**

N/A

2023-01-04 06:35 UTC, LesnyRumcajs approved these changes

2023-01-04 06:35 UTC, LesnyRumcajs commented on CHANGELOG.md
> +* `funty` crate patch.
We should list the changes that actually impact the Forest usage. Internals are not helpful to end users and they kind of bloat the changelog.
```suggestion
* RocksDB check for low file descriptor limit.
* Unused RPC endpoints.
```

2023-01-04 15:22 UTC, lemmih commented on CHANGELOG.md
> +* New daemon option flag `—log-dir` for log file support.
I think your editor changed `--` to `—`.

2023-01-04 15:55 UTC, lemmih requested changes

2023-01-04 15:55 UTC, lemmih commented on CHANGELOG.md
> +* Multiple CI improvements.
The target audience of the changelog are users, not developers. They only care about user-visible changes to Forest.

- They don't care about the DB benchmark script as it is an internal development tool. They don't care which module we use to serialize policies. They _might_ care about the logging framework but that is also borderline.
- The sync issue description is too detailed. It should be much simpler. Something like: `Fixed bug triggered by large network messages.`
- The same goes for the missing cursor. Highlight that it is a bug-fix and keep it short: "Fixed bug where cursor would be hidden after keyboard interrupt."
- Users don't care about `serde_ipld_dagcbor`.
- There are three or four items mentioning improved error messages. They can be merged into one item.
- The caching of cargo bins isn't a user visible change.
- Replacing `difference` with `similar` isn't a user visible change.
- The `net disconnect` bug could be explained in a bit more detail.
- The FIL balance bug fix could be explained in a bit more detail.
- The CI improvements are not user visible.

2023-01-05 09:26 UTC, lemmih commented on CHANGELOG.md
> +* New daemon option flag `-—log-dir` for log file support.
```suggestion
* New daemon option flag `--log-dir` for log file support.
```

2023-01-05 09:28 UTC, lemmih commented on CHANGELOG.md
> +* Restored link to [deps.rs](https://deps.rs/).
The link was removed after `0.5.1` so this line shouldn't be here.

2023-01-05 09:29 UTC, lemmih commented on CHANGELOG.md
> +* Fixed issue with invalid snapshot exports.
What issue? When would this happen?

2023-01-05 09:34 UTC, lemmih commented on CHANGELOG.md
> +* Implemented proper tagging strategy for Docker images.
We can be more explicitly about what "proper tagging" means:

```suggestion
* Docker images are now tagged with version (eg `0.6.0`) and date (eg `2023-01-05-commit_hash`).
```

2023-01-06 09:51 UTC, lemmih approved these changes
I like it. Remember to update the release date (current set to `2023-01-04`) before merging.

Also, could you wrap the lines at 80 or 100 characters. Your editor will have a command for doing this.

2023-01-06 15:53 UTC, merged