Remove forest-fil-types crate and relocate items
ChainSafe/forest pull request #2698
Opened 2023-03-22 12:12 UTC by creativcoder

## Summary of changes

Changes introduced in this pull request:

- Removes forest-fil-types crate and moves items under `state_manager/utils.rs`

## Reference issue to close (if applicable)

Closes #2645 

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation,
- [X] I have added tests that prove my fix is effective or that my feature works
      (if possible),
- [X] I have made sure the
      [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is
      up-to-date. All user-facing changes should be reflected in this document.

2023-03-22 12:19 UTC, lemmih requested changes
Why do these functions belong with the state manager?

2023-03-22 12:19 UTC, lemmih commented on blockchain/state_manager/Cargo.toml
> +filecoin-proofs-api = { workspace = true, default-features = false }
```suggestion
filecoin-proofs-api = { workspace = true }
```

2023-03-22 13:10 UTC, creativcoder commented
I saw various sector info and PoST proof related apis already in state_manager/utils.rs so felt it would be a good place.

2023-03-22 15:44 UTC, lemmih commented
> > Why do these functions belong with the state manager?
> 
> I saw various sector info and PoST proof related apis already in state_manager/utils.rs so felt it would be a good place.

If the state manager was the only consumer of these functions then it would make sense to put them here. But you're exporting the functions and importing them elsewhere. I'm not sure it logically makes sense to associate them with the state manager.

2023-03-23 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/forest?pullRequest=2698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/forest?pullRequest=2698) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/forest?pullRequest=2698) it.</sub>

2023-03-24 13:23 UTC, lemmih requested changes

2023-03-24 13:23 UTC, lemmih commented on blockchain/consensus/fil_cns/src/validation.rs
> +pub fn verify_winning_post(
```suggestion
fn verify_winning_post(
```

2023-03-24 13:23 UTC, lemmih commented on blockchain/state_manager/src/utils.rs
> +pub fn generate_winning_post_sector_challenge(
```suggestion
fn generate_winning_post_sector_challenge(
```

2023-03-24 15:51 UTC, lemmih approved these changes

2023-03-24 15:51 UTC, lemmih commented on blockchain/state_manager/src/utils.rs
> +fn generate_winning_post_sector_challenge(
Could this be inlined?

2023-03-27 08:46 UTC, LesnyRumcajs approved these changes

2023-03-28 08:45 UTC, merged