implement Filecoin.ChainSetHead endpoint
ChainSafe/forest pull request #2821
Opened 2023-05-02 16:24 UTC by aatifsyed

## Summary of changes

Changes introduced in this pull request:

-

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-05-02 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/forest?pullRequest=2821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/forest?pullRequest=2821) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/forest?pullRequest=2821) it.</sub>

2023-05-04 02:02 UTC, aatifsyed commented
Note, CI has flaked:
https://github.com/ChainSafe/forest/actions/runs/4878069115/jobs/8703365437
```
thread 'tests::bitswap_go_compat_test' panicked at 'called `Result::unwrap()` on an `Err` value: deadline has elapsed', node/forest_libp2p/bitswap/tests/go_compat.rs:27:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

   Canceling due to test failure: 0 tests still running
------------
     Summary [  66.565s] 265 tests run: 264 passed, 1 failed, 0 skipped
        FAIL [  65.368s] forest_libp2p_bitswap::go_compat tests::bitswap_go_compat_test
```

I've seen this fail on a local checkout of master too

2023-05-04 05:27 UTC, lemmih requested changes
How about testing it against calibnet by setting the head to a few epochs in the past and then verifying that Forest can re-sync to the most recent epoch?

Regarding non-calibnet testing, I am all ears. Let's discuss ways of testing Forest in slack.

Oh, and let's reset the `yarn.lock` file.

2023-05-04 05:27 UTC, lemmih commented on blockchain/chain/src/store/chain_store.rs
> +    pub fn unmark_block_as_validated(&self, cid: &Cid) -> Result<(), Error> {
Conceptually, it's a mistake that the set of validated blocks is saved to a file. But fixing it depends on issue #2771. Once that issue has been closed, this function will be infallible.

2023-05-04 05:27 UTC, lemmih commented on blockchain/chain/src/store/chain_store.rs
> +            // TODO(aatifsyed): should we return an error if block doesn't exist?
I don't think it's an error if a previously validated block isn't in the set. The set is merely a cache and may be emptied at any point in time.

2023-05-04 08:36 UTC, elmattic requested changes

2023-05-04 08:36 UTC, elmattic commented on node/rpc/src/chain_api.rs
> +// This is basically a port of the go implementation
Note that there is another go implementation (Venus). Feel free to add in a comment a link to the method/commit that has "inspired" you.

2023-05-04 12:12 UTC, LesnyRumcajs reviewed
Looks good, minus test coverage.

2023-05-04 12:12 UTC, LesnyRumcajs commented on forest/cli/src/cli/chain_cmd.rs
> +                assert_eq!(cids.len(), 0, "should be disallowed by clap");
```suggestion
                assert!(cids.is_empty(), "should be disallowed by clap");
```

2023-05-09 10:15 UTC, lemmih approved these changes

2023-05-09 10:57 UTC, elmattic approved these changes

2023-05-09 14:07 UTC, merged