[WIP] Prune direct FVM usage from Forest
ChainSafe/forest pull request #2880
Opened 2023-05-15 19:45 UTC by jdjaustin

## Summary of changes

Changes introduced in this pull request:

- [ ] Re-export all FVM3 structs/constants in the Forest shim and use them in Forest. In the places where we use FVM2, switch to FVM3 and/or use a shim.
- [ ] Impose a strict rule of not using FVM/FVM3 directly with `.clippy`.

## Reference issue to close (if applicable)

Closes #2713 

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-06-05 19:52 UTC, jdjaustin commented
This PR is getting chonky. Might need to split off the `ActorState` changes into their own PR...

2023-06-09 17:57 UTC, lemmih requested changes

2023-06-09 17:57 UTC, lemmih commented on blockchain/state_manager/src/errors.rs
>  }
This can just be deleted.

2023-06-09 18:32 UTC, jdjaustin commented on utils/forest_shim/src/gas.rs
> +pub struct GasTracker(GasTrackerV3);
Ah true, I had done that before we talked about how `forest_interpreter` would also still be allowed to use FVM directly. I'll remove.

2023-06-09 19:03 UTC, lemmih approved these changes

2023-06-12 13:41 UTC, elmattic approved these changes

2023-06-12 13:41 UTC, merged