feat: adaptive window size for tipset syncer
ChainSafe/forest pull request #3129
Opened 2023-07-05 14:59 UTC by hanabi1224

## Summary of changes

Changes introduced in this pull request:

- [x] Implement `AdaptiveValueProvider`
- [x] Tests
- [x] Manually test on mainnet with https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/forest_snapshot_mainnet_2023-06-28_height_2988801.car.zst

## Reference issue to close (if applicable)

Closes https://github.com/ChainSafe/forest/issues/3119

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-07-05 16:19 UTC, hanabi1224 commented on src/utils/misc/value_provider.rs
> +        let old = self.consective_failure_counter.fetch_add(1, ORDERING);
AtomicUsize does not panic abt overflow so no special handling is needed

2023-07-06 06:24 UTC, lemmih commented
I'm not convinced this is the right approach. I don't understand why peers reject requests of 32 blocks, and I'm not sure if we're being a bad network participant by requesting that many blocks. Also, we don't need to request more than the default amount of blocks to fully saturate our pipeline if we use proper streaming logic. The current code is quite awkward and won't request more than 1 batch at a time.

2023-07-06 06:45 UTC, lemmih commented
Let's hold off on merging this until we can benchmark against a streaming solution.

2023-07-06 06:46 UTC, lemmih requested changes
Blocking until we can benchmark against a streaming solution.

2023-07-13 11:17 UTC, closed without merging