Db use two cols
ChainSafe/forest pull request #3160
Opened 2023-07-10 14:24 UTC by LesnyRumcajs

## Summary of changes

Changes introduced in this pull request:

-

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-07-13 15:32 UTC, aatifsyed requested changes
I think I need more background to understand this PR

- What problem are we trying to solve?
- What does it mean to transition to a multi-column database? Why do we need it? What are the tradeoffs? How should we balance that in-code (at the interface level)

Can we think of some other ways to solve the problems we're trying to?
e.g
```rust
pub trait List: Blockstore {
    /// Return all Cids contained in this blockstore
    fn cids(&self) -> Vec<Cid>;
}

// This would compose nicely with e.g progress
// But what are e.g the performance tradeoffs?
pub fn dump(blockstore: impl List, destination: impl Write) {...}
```

2023-07-13 15:54 UTC, ruseinov commented on src/chain/store/chain_store.rs
> +        };
It's a good one. Now that I look at this - it's starting to look troublesome that we have this code snipper all over the place. 

Perhaps we should create a follow-up issue to clean this up, something like this:
1. `fn maybe_compressed(compression: bool)`
2. Make it easy to apply at the [call site](https://github.com/ChainSafe/forest/pull/3160/files#diff-52be9447b2b05d5c8e80758cd43b035f24fb0f1c7cd509aaa37f9912c434cdc4R56) as opposed to embedding it into a variety of methods
3. Clean up all of our internals and move this decision to top-level methods.

2023-07-13 16:06 UTC, ruseinov commented on src/chain/store/chain_store.rs
> +    async fn dump_db_as_car<W>(
After looking at ParityDB's iterators it seems that the iteration order is unspecified. I'm not sure what happens when reading an unordered `.car` file. I would at least test this on a somewhat big database to see how the performance is and whether or not there are any errors. 
2 values in the database might not be enough to surface any problems.

2023-07-13 16:08 UTC, ruseinov commented on src/cli/subcommands/db_cmd.rs
> +                println!("Dumping database to CAR file");
I would refactor this into it's own method for readability. And some documentation would be much appreciated.

2023-07-13 16:18 UTC, ruseinov commented on src/db/rolling/impls.rs
> +        W: futures::AsyncWrite + Send + Unpin + 'static,
Does this need to be `'static`?

2023-07-13 16:23 UTC, ruseinov commented on src/db/parity_db.rs
> +            b"h'nglui mglw'nafh Cthulhu R'lyeh".to_vec(),
I would probably invest some time looking into dumping a bigger database and then trying to read the car file / validate it comparing to what `export` does.

Just to see if there are any performance issues related to the ordering.

2023-07-14 07:32 UTC, LesnyRumcajs commented
> I think I need more background to understand this PR
> 
> * What problem are we trying to solve?
This is an experiment suggested by @lemmih. The idea was that iterating over the entries in the DB and writing them to a CAR file would be faster than walking the entire tree. It is not. (though it uses less memory).

> * What does it mean to transition to a multi-column database? Why do we need it? What are the tradeoffs? How should we balance that in-code (at the interface level). If we're transitioning to a columnar database, does it even make sense to continue with Parity?

I need help understanding the problem here. ParityDb has multi-column support out of the box. Why would we need to switch to something else when introducing more columns? 

The reasons are already commented on in the code. In short, the key (in our case, CIDs) is not retrievable with the current settings (it is not using a BTree storage). Globally changing this incurs a performance penalty, so I introduced another column for entries that cannot be easily reconstructed from their values. An alternative is to embed the codec and hasher into the values themselves which is, subjectively, a worse approach and likely less performant.

If you look at the changes in the code, the public interface to the DB did not change. Only the ParityDb module should know about the existence of many columns and handle them.

> 
> Can we think of some other ways to solve the problems we're trying to? e.g
> 
> ```rust
> pub trait List: Blockstore {
>     /// Return all Cids contained in this blockstore
>     fn cids(&self) -> Vec<Cid>;
> }
> 
> // This would compose nicely with e.g progress
> // But what are e.g the performance tradeoffs?
> pub fn dump(blockstore: impl List, destination: impl Write) {...}
> ```

I'd rather not put on the heap billions of Cids. Memory-wise this would be even more resource-consuming than walking the tree.

2023-07-14 07:56 UTC, lemmih commented
> All in all, given that it is a failed experiment, I'm happy to close this, especially given that it's unlikely anyone will use this at the current stage. I ran it to completion as suggested by @lemmih.

I can live without the `forest-cli db dump` command, but we still want the column re-organization. Iterating over the CIDs in our blockstore is required by the not-yet-implemented garbage collector.

On a side note, I still think this command can be significantly faster than a regular snapshot export. It turned out that the car writer was the bottleneck, but we can totally fix that.

2023-07-14 08:11 UTC, LesnyRumcajs commented
> On a side note, I still think this command can be significantly faster than a regular snapshot export. It turned out that the car writer was the bottleneck, but we can totally fix that.

It wasn't that much of a bottleneck. Even with a dummy sink (and not re-creating the Cids) the dump time was "only" 50%  faster than a regular export. But yeah, we can revisit this in the future.

2023-07-14 08:13 UTC, LesnyRumcajs commented
> I can live without the forest-cli db dump command, but we still want the column re-organization. Iterating over the CIDs in our blockstore is required by the not-yet-implemented garbage collector.

Closing. I'll push the DB-reorg with some additional changes in another PR.

2023-07-14 08:13 UTC, closed without merging