Consume upstream `quickcheck` implementation for `Cid`
ChainSafe/forest pull request #3162
Opened 2023-07-10 18:10 UTC by jdjaustin

## Summary of changes

Changes introduced in this pull request:
- Remove custom quickcheck implementation for `Cid` and use the upstream implementation

## Reference issue to close (if applicable)

Closes associated task in #2143 

## Other information and links

N/A

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-07-10 19:18 UTC, lemmih requested changes
There's also `ArbitraryCid` to be deleted.

2023-07-10 19:59 UTC, lemmih commented on src/blocks/gossip_block.rs
> +        let secp_cids: Vec<Cid> = Vec::arbitrary(g);
You could even inline these.

2023-07-10 20:26 UTC, lemmih approved these changes

2023-07-10 20:26 UTC, lemmih commented on src/blocks/tipset.rs
>              Self { cids }
```suggestion
            Self { cids: Vec::arbitrary(g) }
```

2023-07-11 05:55 UTC, LesnyRumcajs approved these changes

2023-07-11 06:17 UTC, merged