Consume upstream `quickcheck` implementation for `Ipld`
ChainSafe/forest pull request #3164
Opened 2023-07-10 22:19 UTC by jdjaustin

## Summary of changes

Changes introduced in this pull request:

- Remove custom quickcheck implementation for `Ipld` and use the upstream implementation

## Reference issue to close (if applicable)

Closes associated task in #2143 

## Other information and links

N/A

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-07-12 06:29 UTC, lemmih requested changes

2023-07-12 06:29 UTC, lemmih commented on src/ipld/json.rs
> +        // Filter out problematic NaN values.
I'd say something like `Reject Ipld input containing NaN floats`. In my mind, filtering out values would mean returning a new `Ipld` structure without the problematic floats.

2023-07-12 06:29 UTC, lemmih commented on src/ipld/json.rs
> +        // Filter out problematic NaN values.
Also, write a note about _why_ you're rejecting NaN input.

2023-07-13 13:34 UTC, lemmih approved these changes

2023-07-13 15:16 UTC, aatifsyed approved these changes

2023-07-13 15:19 UTC, aatifsyed approved these changes

2023-07-13 15:19 UTC, aatifsyed commented on src/ipld/json.rs
> +        let serialized: String = serde_json::to_string(&IpldJsonRef(&ipld)).unwrap();
```suggestion
        let serialized = serde_json::to_string(&IpldJsonRef(&ipld)).unwrap();
```

2023-07-13 15:20 UTC, sudo-shashank approved these changes

2023-07-13 17:50 UTC, merged