feat: add --depth flag to snapshot export
ChainSafe/forest pull request #3330
Opened 2023-08-07 06:38 UTC by lemmih

## Summary of changes

Changes introduced in this pull request:

- A depth of 2000 is the default but other depths are useful. This PR adds a flag to using a custom depth when exporting.

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-08-07 15:50 UTC, jdjaustin commented on src/cli/subcommands/snapshot_cmd.rs
> +        /// How many state-roots to include. Lower limit is 900 for `calibnet` and `mainnet`.
Do you think there should be some sort of warning if the user provides a depth <900? With the current changes, this is the behavior on my machine if I do so, and I wouldn't know why it's "failing" without reading the code comment:
<img width="495" alt="Screen Shot 2023-08-07 at 10 45 19 AM" src="https://github.com/ChainSafe/forest/assets/11778588/ecd38d93-e48a-4852-9888-aa9eb0ab2755">

2023-08-07 15:53 UTC, jdjaustin requested changes

2023-08-07 15:53 UTC, jdjaustin commented on CHANGELOG.md
> +- [#3330](https://github.com/ChainSafe/forest/pull/3330): Add `--diff` flag to
```suggestion
- [#3330](https://github.com/ChainSafe/forest/pull/3330): Add `--depth` flag to
```

2023-08-08 14:49 UTC, ruseinov approved these changes

2023-08-08 15:05 UTC, jdjaustin approved these changes

2023-08-09 07:51 UTC, LesnyRumcajs approved these changes

2023-08-09 11:27 UTC, merged