Remove consensus trait
ChainSafe/forest pull request #3342
Opened 2023-08-08 13:34 UTC by creativcoder

## Summary of changes

Changes introduced in this pull request:

- Removes consensus trait
- replaces Beacon constraint with dyn Beacon.

## Reference issue to close (if applicable)

Closes #3198 

## Other information and links

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation,
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-08-09 13:15 UTC, lemmih requested changes
The discussion moved to Slack.

2023-08-14 10:00 UTC, lemmih requested changes

2023-08-14 10:00 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +    // let consensus = Arc::clone(&consensus);
```suggestion
```

2023-08-14 10:00 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +    // let consensus = consensus.clone();
```suggestion
```

2023-08-14 10:00 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +    consensus: Arc<FilecoinConsensus>,
The `consensus` argument is not required here. You can create a new `FilecoinConsensus` structure from the beacon in the state manager. Removing the `consensus` argument will have a ripple effect on the rest of the code.

2023-08-14 11:15 UTC, lemmih commented on src/cli/subcommands/snapshot_cmd.rs
> +    if FETCH_PARAMS {
`FETCH_PARAMS` is always true. Let's unroll the code.

2023-08-14 13:14 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +        .map(|batch| fetch_batch::<_>(batch, &network, db))
```suggestion
        .map(|batch| fetch_batch(batch, &network, db))
```

2023-08-14 13:14 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +                validate_tipset::<_>(
```suggestion
                validate_tipset(
```

2023-08-14 13:14 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +            tokio::task::spawn(validate_block::<_>(state_manager.clone(), Arc::new(b)));
```suggestion
            tokio::task::spawn(validate_block(state_manager.clone(), Arc::new(b)));
```

2023-08-14 13:15 UTC, lemmih commented on src/chain_sync/tipset_syncer.rs
> +    validations.push(tokio::task::spawn(check_block_messages::<_>(
```suggestion
    validations.push(tokio::task::spawn(check_block_messages(
```

2023-08-14 13:17 UTC, lemmih approved these changes

2023-08-16 14:40 UTC, sudo-shashank approved these changes

2023-08-16 15:19 UTC, merged