feat: refactor current db into ManyCar<ParityDB>
ChainSafe/forest pull request #3349
Opened 2023-08-09 14:52 UTC by hanabi1224

## Summary of changes

As part of https://github.com/ChainSafe/forest/issues/3334
After https://github.com/ChainSafe/forest/pull/3328 being merged, generic blockstores no longer requires `Clone`, thus we can refactor the current DB from `ParityDB` into `ManyCar<ParityDB>` which could serve forest CAR directly instead of loading it into pairty-db

Changes introduced in this pull request:

- refactor current db into ManyCar<ParityDB>

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-08-09 18:32 UTC, lemmih requested changes
The garbage collector should not be aware of the CAR files. How about changing the stack from `RollingDB<ManyCar<ParityDB>>` to `ManyCar<RollingDB<ParityDB>>`? Or we could also just delete the garbage collector altogether.

2023-08-10 00:04 UTC, hanabi1224 commented
> The garbage collector should not be aware of the CAR files. How about changing the stack from `RollingDB<ManyCar<ParityDB>>` to `ManyCar<RollingDB<ParityDB>>`? Or we could also just delete the garbage collector altogether.

@lemmih Changed to ManyCar<RollingDB>

2023-08-10 07:10 UTC, lemmih commented on src/db/car/many.rs
> +    writer: RwLock<WriterT>,
No need for this to be locked anymore.

```suggestion
    writer: WriterT,
```

2023-08-10 10:44 UTC, aatifsyed approved these changes

2023-08-10 10:48 UTC, lemmih approved these changes

2023-08-10 11:55 UTC, merged