fix: move actor bundles to git lfs
ChainSafe/forest pull request #3360
Opened 2023-08-11 11:42 UTC by hanabi1224

## Summary of changes

Changes introduced in this pull request:

- Move actor bundles to git lfs to avoid doing CAR related stuff in `build.rs`

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-08-11 11:54 UTC, aatifsyed approved these changes

2023-08-11 12:59 UTC, lemmih requested changes

2023-08-14 08:16 UTC, hanabi1224 commented on .github/workflows/checkpoints.yml
> +          lfs: true
Removed

2023-08-14 10:18 UTC, aatifsyed approved these changes

2023-08-14 10:21 UTC, lemmih approved these changes
Nice. Thank you.

2023-08-14 10:44 UTC, merged