ensure git-lfs is installed to avoid confusing errors
ChainSafe/forest pull request #3400
Opened 2023-08-18 16:17 UTC by LesnyRumcajs

## Summary of changes

Changes introduced in this pull request:

- This is to avoid confusing errors when `git-lfs` is not installed, e.g., 
```
--> src/daemon/bundle.rs:16:5
  |
16 |   const_assert_eq!(ACTOR_BUNDLES_CAR_ZST.len(), 2438387);
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `0_usize - 1_usize`, which would overflow
```
even on a new git clone.

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2023-08-18 16:44 UTC, elmattic approved these changes

2023-08-19 20:38 UTC, hanabi1224 commented
cargo install forest-filecoin should not require git-lfs

2023-08-21 08:18 UTC, jdjaustin approved these changes

2023-08-21 09:11 UTC, aatifsyed requested changes
+1 for `cargo install` not requiring `git lfs`

2023-08-21 10:26 UTC, LesnyRumcajs commented
> cargo install forest-filecoin should not require git-lfs
> +1 for cargo install not requiring git lfs

@hanabi1224 @aatifsyed And how would you achieve this? I encourage you to remove `git-lfs` from your system temporarily, git clone a new repo and run `make install`. This is what triggered this change.

2023-08-21 10:31 UTC, aatifsyed commented
We have two end-user install pathways:
- `git clone ... && make install`
- `cargo install forest-filecoin`

If a user performed the latter, they would erroneously require git-lfs, even though git isn't in the loop - the bundle is in the cargo package. 

I'd need to know more about the code that includes the actor bundles, but I suspect it's a case of checking that they're there already or something. 

(Note that I don't think we should support `cargo install` in general - it's causing a lot of warts like this >.<)

2023-08-21 10:33 UTC, aatifsyed commented
Having read the above, maybe my comment is a bit of a nit "we don't require exactly the minimal number of installation dependencies"

2023-08-21 10:44 UTC, LesnyRumcajs commented
> We have two end-user install pathways:
> 
> * `git clone ... && make install`
> * `cargo install forest-filecoin`
> 
> If a user performed the latter, they would erroneously require git-lfs, even though git isn't in the loop - the bundle is in the cargo package.

I understand now, thanks. It's a valid concern. I don't quite know how to get around this without nastily exposing Forest internals to the build script.

2023-08-21 12:08 UTC, hanabi1224 commented
> I understand now, thanks. It's a valid concern. I don't quite know how to get around this without nastily exposing Forest internals to the build script.

@LesnyRumcajs How about checking bundle size before `git-lfs`, in case bundle size is invalid, `cargo publish` would fail, and the published crate should always have correct bundle size thus `git-lfs` check would be bypassed

2023-08-21 12:42 UTC, LesnyRumcajs commented
> > I understand now, thanks. It's a valid concern. I don't quite know how to get around this without nastily exposing Forest internals to the build script.
> 
> @LesnyRumcajs How about checking bundle size before `git-lfs`, in case bundle size is invalid, `cargo publish` would fail, and the published crate should always have correct bundle size thus `git-lfs` check would be bypassed

I don't think I get it. We are already checking the bundle size, and ending up with the cryptic message in the PR description, no?

2023-08-21 13:09 UTC, hanabi1224 commented
> I don't think I get it. We are already checking the bundle size, and ending up with the cryptic message in the PR description, no?

@LesnyRumcajs If we move the bundle size check to the build script, we don't have to use `const_assert_eq!`, a normal `assert_eq!` with error message would just work

2023-08-29 14:11 UTC, elmattic approved these changes

2023-08-29 14:22 UTC, aatifsyed commented on build.rs
> +}
should probably even be `fn check_bundle` - we don't capture any state

2023-08-29 15:12 UTC, LesnyRumcajs commented on build.rs
> +}
So now I'm reviewing your code in my code review? That's proper reviewoception

2023-08-30 07:47 UTC, merged