Restore old height infos
ChainSafe/forest pull request #4091
Opened 2024-03-21 09:23 UTC by elmattic

## Summary of changes

This PR is a follow-up of #4080, which was restoring the `Liftoff` height entry.

Changes introduced in this pull request:

- Restore `Breeze`, `Smoke`, and `Ignition` entries for _Calibnet_

Those heights are used at different places in the protocol and can have a significant impact, too.

I'm not sure if we also want to restore them for _Devnet_ and _Butterflynet_.

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-03-21 09:29 UTC, hanabi1224 commented on CHANGELOG.md
> +- [#3727](https://github.com/ChainSafe/forest/pull/3727) Added glif.io the c
c?

2024-03-21 09:29 UTC, hanabi1224 commented on CHANGELOG.md
> +  Forest on the c using a configuration file only.
c?

2024-03-21 09:36 UTC, hanabi1224 approved these changes

2024-03-21 09:43 UTC, LesnyRumcajs requested changes
What about Butterflynet and Devnet? These (and Liftoff) should be marked as mandatory, preferably via static checks or tests, so that `HEIGHT_INFOS` is invalid without them.

2024-03-21 15:42 UTC, elmattic commented
@LesnyRumcajs, do you have any idea why Devnet checks failed?

2024-03-21 19:28 UTC, LesnyRumcajs commented
> @LesnyRumcajs, do you have any idea why Devnet checks failed?

Yes. I'll send a PR your way soon.

2024-03-21 21:44 UTC, LesnyRumcajs commented
@elmattic https://github.com/ChainSafe/forest/pull/4097 Please take a look to see if the change makes sense. If so, feel free to merge it with your branch.

2024-03-22 09:42 UTC, elmattic commented
Thanks! @LesnyRumcajs

2024-03-22 10:49 UTC, LesnyRumcajs approved these changes

2024-03-22 11:05 UTC, merged