feat: log inner error in additon to the context
ChainSafe/forest pull request #4128
Opened 2024-04-01 10:01 UTC by hanabi1224

## Summary of changes

Changes introduced in this pull request:

-

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-04-02 09:39 UTC, aatifsyed requested changes
I don't think we should do this (or I don't understand the problem enough).

```rust
let e: anyhow::Result;
tracing::error(?e, "error doing foo");
```

This gives us the desired formatting:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b139670fd7096276d92c0da257608a86

If you really want to do it this way, I would have a shim around anyhow::Error that just changed the formatting params

2024-04-04 10:06 UTC, LesnyRumcajs commented
How it's done is a detail. The fact that we need to use the `Debug` to get the full trace is non-intuitive, making the current error messages difficult to reason about.

Either this change needs to be implemented, one way or another, or all error messages should use the `?e` or a variant of that. If we do the latter, it should be enforced in CI. As discussed with @hanabi1224 in Slack, our expectation is that the `Display` of an error is a sum of its errors, not just the top-level context, which is rarely useful on its own.

2024-04-04 12:52 UTC, aatifsyed approved these changes
Fine with this as an interim measure, but prefer #4143

2024-04-22 01:25 UTC, hanabi1224 commented
Superseded by https://github.com/ChainSafe/forest/pull/4174

2024-04-22 01:25 UTC, closed without merging