feat(rpc): implement Filecoin.StateListActors
ChainSafe/forest pull request #4409
Opened 2024-06-12 07:28 UTC by hanabi1224

## Summary of changes

Changes introduced in this pull request:

- implement RPC method `Filecoin.StateListActors`
- API compare tests

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-06-12_height_1694998.forest.car.zst --filter StateListActors`
| RPC Method                    | Forest | Lotus |
|-------------------------------|--------|-------|
| Filecoin.StateListActors (10) | Valid  | Valid |
```

## Reference issue to close (if applicable)

Closes

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-06-12 09:25 UTC, lemmih approved these changes

2024-06-12 14:06 UTC, ruseinov approved these changes

2024-06-12 14:06 UTC, ruseinov requested changes
Missing a CHANGELOG entry.

2024-06-12 14:07 UTC, aatifsyed approved these changes

2024-06-13 08:54 UTC, ruseinov commented
> > Missing a CHANGELOG entry.
> 
> @ruseinov I'd prefer not to bloat the changelog(and create potential merge conflicts with others) with an entry for each individual RPC method, maybe better to use a milestone entry instead. Note that we still have the detailed autogenerated changelog for each PR on the release page. Echoing @lemmih 's comment [here](https://github.com/ChainSafe/forest/pull/4039#issuecomment-1983686248)
> 
> > I'm okay with not having a changelog entry for each RPC method. Instead, we'll have an entry for each RPC milestone (full v0, full v1, full lotus compliance, etc).

I mean we used to put every RPC endpoint into CHANGELOG till now, I see no reason in changing that now.

2024-06-13 08:55 UTC, ruseinov approved these changes

2024-06-15 09:16 UTC, merged