feat(rpc): implement `MpoolBatchPush` and `MpoolBatchPushUntrusted`
ChainSafe/forest pull request #4561
Opened 2024-07-18 11:45 UTC by lemmih

## Summary of changes

Changes introduced in this pull request:

- Both methods are vectorized versions of `MpoolPush` and `MpoolPushUntrusted`.
- Still no tests for the mpool methods. :(

## Reference issue to close (if applicable)

Closes #4549 and #4546

## Other information and links

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation,
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-07-18 13:11 UTC, hanabi1224 approved these changes

2024-07-18 15:25 UTC, aatifsyed commented on src/rpc/methods/mpool.rs
> +    const PERMISSION: Permission = Permission::Read;
This is only true if we have the same trust model for both types of access, which isn't true.

Consider this network topology for a node:
```console
$ ufw allow from 10.0.1.0/24 to any port 1234 proto tcp # allow RPC access from 10.0.1.x
$ ufw allow from 10.0.2.0/24 to any port # allow libP2P access from 10.0.2.x
```

If I trust `1.x` and `2.x` with different things, then this breaks my trust.

2024-07-18 15:27 UTC, aatifsyed requested changes

2024-07-18 15:27 UTC, aatifsyed commented on src/rpc/methods/mpool.rs
> +    const PERMISSION: Permission = Permission::Read;
This is only true if we have the same trust model for both types of access, which isn't true.

Consider this network topology for a node:
```console
$ ufw allow from 10.0.1.0/24 to any port 1234 proto tcp # allow RPC access from 10.0.1.x
$ ufw allow from 10.0.2.0/24 to any port # allow libP2P access from 10.0.2.x
```

If I trust `1.x` and `2.x` with different things, then this breaks my trust.

2024-07-18 15:55 UTC, aatifsyed approved these changes

2024-08-21 15:06 UTC, aatifsyed commented
@lemmih what's the status on this?

2024-08-23 11:38 UTC, lemmih commented
Situation: Lotus requires `write` permissions for the `MpoolPush` family of RPC methods. This doesn't make sense, and public RPC providers (such as glif.io) have modded them to be read-access. For now, we'll match Lotus' behavior and let the node providers deal with it.

This PR is ready to be merged.

2024-08-23 11:39 UTC, lemmih commented
The wallet documentation is still valid even after changing the required permissions from `Read` to `Write`.

2024-08-23 11:43 UTC, LesnyRumcajs approved these changes
What plans do we have for testing this?

2024-08-23 12:14 UTC, lemmih commented
> What plans do we have for testing this?

I'm hoping we can steal some tests from Curio. They (indirectly) test message pushing.

2024-08-23 12:30 UTC, merged