feat(tool): forest-tool api generate-test-snapshot
ChainSafe/forest pull request #5074
Opened 2024-12-11 12:45 UTC by hanabi1224

## Summary of changes

This PR includes changes in #5034

Changes introduced in this pull request:

- `forest-tool api generate-test-snapshot`
- `forest-tool api test`
- a few RPC unit tests (to be expanded with the manual steps below)

(Will use a separate PR to add below steps to dev docs)

### Step 1: generating RPC test dumps
`forest-tool api compare --dump-dir /var/tmp/rpc-dumps ...`

### Step 2: generate RPC test snapshots
`forest-tool api generate-test-snapshot --db ~/.local/share/forest/calibnet/0.23.0 --chain calibnet --out-dir /var/tmp/rpc-snapshots /var/tmp/test-dumps/filecoin_stategetallallocations*.json`

### Step 2(b): zstd compress test snapshots
```
cd /var/tmp/rpc-snapshots
zstd *.json
``` 

### Step 3: verify test snapshots
`forest-tool api test /var/tmp/rpc-snapshots/*.json` or `forest-tool api test /var/tmp/rpc-snapshots/*.zst`

### Step 3(b): update unit test
- upload test snapshots to DO space
- update `test_snapshots.txt`
- `cargo test --lib -- --test rpc_regression_tests --nocapture`

## Reference issue to close (if applicable)

Closes #5034

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-12-12 09:36 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd/generate_test_snapshot.rs
> +        // HACKHACK: may need some care
We could deal with these `HACKHACK` later when they are used by some RPC methods and the snap generation flow fails

2024-12-12 09:37 UTC, lemmih requested changes
The format of the memory-db is not stable. If someone changes the memory-db internals, this code will fail. We'll either have to deal with it right now or in the future. I vote to deal with it right now.

2024-12-16 08:28 UTC, hanabi1224 commented
> The format of the memory-db is not stable. If someone changes the memory-db internals, this code will fail. We'll either have to deal with it right now or in the future. I vote to deal with it right now.

@lemmih Switched to Forest CAR DB as discussed.

2025-01-09 12:49 UTC, LesnyRumcajs commented on src/db/memory.rs
> +}
Can we contrive a unit test for this functionality?

2025-01-09 12:51 UTC, LesnyRumcajs commented on src/tool/subcommands/api_cmd.rs
> +        test_dump_files: Vec<PathBuf>,
Let's have docs for this as well.

2025-01-09 12:51 UTC, LesnyRumcajs commented on src/tool/subcommands/api_cmd.rs
> +        files: Vec<PathBuf>,
Let's have docs for this as well.

2025-01-09 13:01 UTC, LesnyRumcajs commented on src/tool/subcommands/api_cmd/generate_test_snapshot.rs
> +    let chain_config = Arc::new(ChainConfig::calibnet());
The chain config should depend on the `chain` parameter, no?

2025-01-09 13:11 UTC, LesnyRumcajs commented on src/tool/subcommands/api_cmd/test_snapshot.rs
> +        }
If I understand correctly, each test invocation will temporarily download the snapshots. The total snapshot size currently is around 4 MB, but I can easily see it going higher once we add more snapshots. This will be a pain for someone on a worse connection just trying to run tests.

Perhaps we could add something like `/.local/share/forest-dev/rpc-regression-snapshots` persistent path (it would vary from system to system, we could re-use the logic we have for the DB).

2025-01-09 13:12 UTC, LesnyRumcajs reviewed
Great stuff

2025-01-10 08:50 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd/generate_test_snapshot.rs
> +        // HACKHACK: may need some care
Methods that read settings are no longer supported after migrating DB snapshot to CAR format

2025-01-10 08:51 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd/generate_test_snapshot.rs
> +        // HACKHACK: may need some care
Resolved or removed all HACKHACKs, methods that read settings are no longer supported after migrating DB snapshot to CAR format.

2025-01-10 09:13 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd/generate_test_snapshot.rs
> +    let chain_config = Arc::new(ChainConfig::calibnet());
Good catch, fixed!

2025-01-10 09:16 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd.rs
> +        test_dump_files: Vec<PathBuf>,
Fixed.

2025-01-10 09:16 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd.rs
> +        files: Vec<PathBuf>,
Fixed.

2025-01-10 10:42 UTC, hanabi1224 commented on src/tool/subcommands/api_cmd/test_snapshot.rs
> +        }
Cache implemented.

2025-01-13 09:05 UTC, lemmih approved these changes
LGTM

2025-01-13 09:45 UTC, LesnyRumcajs approved these changes

2025-01-13 10:29 UTC, merged