feat(rpc): add StateMinerInitialPledgeForSector method
ChainSafe/forest pull request #5096
Opened 2024-12-18 06:03 UTC by virajbhartiya

## Summary of changes

Changes introduced in this pull request:

- Implements `StateMinerInitialPledgeForSector`

## Reference issue to close (if applicable)

Closes #4907 

## Other information and links

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

2024-12-18 09:26 UTC, elmattic commented
I don't see the different checks that Lotus is doing:

```
	if sectorDuration <= 0 {
		return types.EmptyInt, xerrors.Errorf("sector duration must greater than 0")
	}
	if sectorSize == 0 {
		return types.EmptyInt, xerrors.Errorf("sector size must be non-zero")
	}
	if verifiedSize > uint64(sectorSize) {
		return types.EmptyInt, xerrors.Errorf("verified size must be less than or equal to sector size")
	}
```
Don't we need them?

2024-12-18 13:14 UTC, virajbhartiya commented
@elmattic added these checks

2024-12-18 16:16 UTC, elmattic requested changes

2024-12-18 16:16 UTC, elmattic commented on src/rpc/methods/state.rs
> +        let sec_size: u64 = match sector_size {
Could we move this to another place? Maybe in some method.

2024-12-18 16:18 UTC, elmattic commented on src/rpc/methods/state.rs
> +        let sec_size: u64 = match sector_size {
Or more simply use `as u64`.

2024-12-18 16:22 UTC, elmattic commented on src/rpc/methods/state.rs
> +        if sec_size < verified_size {
I would stick to `>` in the test. It reduces cognitive load during Rust/Go code comparison.

2024-12-18 16:43 UTC, elmattic commented on src/rpc/methods/state.rs
> +                power_state.ramp_start_epoch(),
Lotus is using some ramp but not us. Please see.

https://github.com/filecoin-project/lotus/blob/a5847457fd2e143d643a1a8326797e4402d2c527/node/impl/full/state.go#L1588

2024-12-19 11:58 UTC, elmattic commented on src/rpc/methods/state.rs
> +                power_state.ramp_start_epoch(),
Please carefully review the Lotus method implementation at line 1558. I don't think we are calculating those variables the same way:

`epochsSinceRampStart, rampDurationEpochs, err := a.getPledgeRampParams(ctx, ts.Height(), state)`

Lotus is calling some `getPledgeRampParams` function.

2024-12-20 12:10 UTC, elmattic commented on src/rpc/methods/state.rs
> +async fn get_pledge_ramp_params(
We don't need the function to be `async` here.

2024-12-20 12:11 UTC, elmattic commented on src/rpc/methods/state.rs
> +) -> Result<(i64, u64), anyhow::Error> {
We can use the `ChainEpoch` type alias instead of `i64` for better clarity

2024-12-20 12:15 UTC, elmattic commented on src/rpc/methods/state.rs
> +        let (epochs_since_start, duration) = get_pledge_ramp_params(&ctx, ts.epoch(), &ts).await?;
nit: move the `let` binding closer to its usage for improved readability.

2024-12-20 12:17 UTC, elmattic commented on src/rpc/methods/state.rs
> +        let sec_size: u64 = sector_size as u64;
nit: Inline the `as` expression directly into the comparison below.

2024-12-20 12:45 UTC, elmattic commented
lgtm. Just a lint error to fix for the CI to pass successfully.

2024-12-20 14:00 UTC, virajbhartiya commented
@lemmih can you please take a look once

2024-12-20 14:08 UTC, elmattic approved these changes

2025-01-07 13:27 UTC, LesnyRumcajs commented on src/rpc/methods/state.rs
> +        .map_err(|e| anyhow::anyhow!("loading power actor state: {e}"))?;
nit: you could use `anyhow`s context.

2025-01-07 13:29 UTC, LesnyRumcajs commented on src/rpc/methods/state.rs
> +        }
nit: you could use `ensure!`

2025-01-08 09:50 UTC, LesnyRumcajs commented on src/rpc/methods/state.rs
> +        }
Indeed!

2025-01-08 09:51 UTC, LesnyRumcajs commented
@virajbhartiya Could you please format the code so that it passes the lint checks?

2025-01-08 12:14 UTC, merged